# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GibbsNormal <- function(x, init, mu0, sigma20, a, b, iter) {
    .Call('_mysample_GibbsNormal', PACKAGE = 'mysample', x, init, mu0, sigma20, a, b, iter)
}

timesTwo <- function(x) {
    .Call('_mysample_timesTwo', PACKAGE = 'mysample', x)
}

